ad/urls.py
from django.urls import path

from . import views

app_name = 'ad'
urlpatterns = [
    path(
        'mitarbeiter/',
        views.MitarbeiterListe.as_view(),
        name="mitarbeiterliste"
    ),
    path(
        'mitarbeiter/<int:pk>/',
        views.MitarbeiterDaten.as_view(),
        name="mitarbeiterdaten"
    ),
    path(
        'mitarbeiter/neu/',
        views.MitarbeiterNeu.as_view(),
        name="mitarbeiterneu"
    ),
]

gll_backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ad/', include('ad.urls')),
]

ad/models.py
from django.db import models

class Mitarbeiter(models.Model):
    GENDER_CHOICES = [
        ('f', 'Frau'),
        ('m', 'Herr'),
        ('d', '*'),
    ]
    KINDS_OF_DEPLOYMENT = [
        ('h', 'Helfer*in'),
        ('a', 'Angestellt'),
        ('f', 'FSJ'),
    ]
    anrede = models.CharField(
        max_length=1,
        choices=GENDER_CHOICES,
        default='d',
    )
    vorname = models.CharField(max_length=20)
    nachname = models.CharField(max_length=30)
    nr = models.CharField(
        max_length=5,
        blank=True,
        help_text='Bei gleichen Vor- und Nachnamen'
    )
    adresszusatz = models.CharField(max_length=20, blank=True)
    strasse = models.CharField(max_length=50)
    pLZ = models.CharField(max_length=5)
    ort = models.CharField(max_length=20)
    telefon = models.CharField(max_length=20, blank=True)
    handy = models.CharField(max_length=20, blank=True)
    email = models.EmailField(blank=True)
    geboren = models.DateField()
    eintritt = models.DateField()
    austritt = models.DateField(blank=True, null=True)
    iBAN = models.CharField(max_length=34)
    bankname = models.CharField(max_length=30)
    art = models.CharField(
        max_length=1,
        choices=KINDS_OF_DEPLOYMENT,
        default='h',
    )
    personenkonto = models.CharField(max_length=20, blank=True)
    stundenlohn = models.CharField(max_length=10, blank=True)
    limit = models.CharField(
        'Jahreslimit für Aufwandsentschädigung',
        max_length=5,
        blank=True
    )
    gesperrt = models.BooleanField(
        'Verdienstabrechnung gesperrt',
        default=False
    )
    meldung = models.TextField('Meldung bei Verdienstabrechnung', blank=True)
    notizen = models.TextField('AD-Notizen', blank=True)
    

ad/views.py
from django.shortcuts import render
from django.views import generic

from django.urls import reverse

from .models import Mitarbeiter

class MitarbeiterListe(generic.ListView):
    model = Mitarbeiter
    

class MitarbeiterDaten(generic.edit.UpdateView):
    model = Mitarbeiter
    fields = '__all__'
    localized_fields = ['geboren', 'eintritt', 'austritt']
    
    def get_success_url(self):
        return reverse('ad:mitarbeiterdaten', args=[self.object.id])
    
    
class MitarbeiterNeu(generic.edit.CreateView):
    model = Mitarbeiter
    fields = '__all__'
    localized_fields = ['geboren', 'eintritt', 'austritt']
    
    def get_success_url(self):
        return reverse('ad:mitarbeiterliste')

ad/templates/ad/mitarbeiter_form.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Mitarbeiter</title>
  </head>
  <body>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Speichern">
    </form>
  </body>
</html>

ad/templates/ad/mitarbeiter_list.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Mitarbeiter</title>
  </head>
  <body>
    <form action={% url 'ad:mitarbeiterneu' %} method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-default">
          Neue*r Mitarbeiter*in
        </button>
    </form>
    {% if object_list %}
        <ul>
        {% for mitarbeiter in object_list %}
            <li>
                <a href={% url 'ad:mitarbeiterdaten' mitarbeiter.id %}>
                    {{ mitarbeiter.nachname }}
                </a>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Bisher gibt es noch keine Mitarbeiter.</p>
    {% endif %}
  </body>
</html>